sudo: false
language: ruby
rvm:
  - 3.1.0
  - 3.0.3
  - 3.0.2
  - 3.0.1
  - 3.0.0
  - 2.7.5
  - 2.7.4
  - 2.7.3
  - 2.7.2
  - 2.7.1
  - 2.7.0
  - 2.6.9
  - 2.6.8
  - 2.6.7
  - 2.6.6
  - 2.6.5
  - 2.6.4
  - 2.6.3
  - 2.6.2
  - 2.6.1
  - 2.6.0
  - 2.5.9
  - 2.5.8
  - 2.5.7
  - 2.5.6
  - 2.5.5
  - 2.5.4
  - 2.5.3
  - 2.5.2
  - 2.5.1
  - 2.5.0
